# Generated by Django 4.0.5 on 2022-08-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email_field',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
