# Generated by Django 4.0.5 on 2022-08-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='timestamp',
        ),
    ]
