# Generated by Django 4.0.5 on 2022-09-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_january'),
    ]

    operations = [
        migrations.CreateModel(
            name='August',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_bills', models.CharField(max_length=255)),
                ('fixed_bills_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='July',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_bills', models.CharField(max_length=255)),
                ('fixed_bills_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='June',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_bills', models.CharField(max_length=255)),
                ('fixed_bills_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_date', models.DateField(blank=True)),
            ],
        ),
    ]
